# This is a basic workflow to help you get started with Actions

name: CI_for_automated_micro_services_provision

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: linux-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Kube Cluster
      - name: Setup Kube Cluster & Pre-Reqs
        run: bash ./scripts/staging_setup_kube_cluster.sh

      # Install|Update Fluxctl
      - name: Install|Update Flux
        run: bash ./scripts/install_flux.sh

      # Configure gh cli
      - name: Configure GH CLI
        run: bash ./scripts/install_configure_gh_cli.sh

      # Setup flux
      - name: Setup flux
        run: bash ./scripts/staging_flux_setup.sh

      # # Remove Kube Cluster
      # - name: Remove Kube Cluster
      #   run: |
      #     bash ./scripts/delete_kube_cluster.sh
      #     tput setaf 2; echo "====================Kind Kubernetes Cluster Removed!===================="
